name = "QuantumGameOfLife"
uuid = "3c172aae-0291-445d-b81a-f9b68f7ccd08"

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
DefaultApplication = "3f0dd361-4fe0-5fc6-8523-80b14ec94d85"
ITensorMPS = "0d1a4710-d33b-49a5-8f18-73bdf49b47e2"
ITensors = "9136182c-28ba-11e9-034c-db9fb085ebd5"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
KrylovKit = "0b1a1467-8014-51b9-945f-bf0ae24f4b77"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SplitApplyCombine = "03a91e81-4c3e-53e1-a0a4-9c0c8f19dd66"
TensorTimeSteps = "1f4dac17-e489-46a5-8247-1c82af6382b6"
